[package]
name = "doppel-admin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
doppel-core = { path = "../doppel-core" }
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
tower.workspace = true

[lints]
workspace = true
