[package]
name = "doppel-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
doppel-core = { path = "../doppel-core" }
doppel-render = { path = "../doppel-render" }
axum.workspace = true
futures-util.workspace = true
rand.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
metrics.workspace = true
regex.workspace = true
tower.workspace = true

[lints]
workspace = true
