#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""Regenerate docs/usage/parameters.md from doppel-config.schema.json.

    uv run scripts/parameters_doc.py            # write the file
    uv run scripts/parameters_doc.py --check    # fail if it is out of date

One section per configuration parameter: what it is, its type, whether it is
required, the bounds on it, and an example in place. Generated rather than written
because the source of every one of those facts is already the schema, which is
generated from the Rust types that enforce them -- a hand-written page would be a
third copy, and the one nobody runs drifts first.

The anchors are the other reason. The dashboard puts an (i) beside a field and links
it here, so every parameter needs an anchor that is predictable from its path:
`proxies[].mocks[].request.url` is `#proxies-mocks-request-url`. Brackets go, dots
become dashes. `scripts/check_docs_links.py` holds the page and the frontend to that.

Prose stays in usage/configuration.md and the guides. This page is the reference you
look a field up in, not the page you learn the system from.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "doppel-config.schema.json"
OUTPUT = ROOT / "docs" / "usage" / "parameters.md"

HEADER = """<!--
  Generated by scripts/parameters_doc.py from doppel-config.schema.json.
  Do not edit by hand: `make gate` fails when this file and the schema disagree.
-->

# Every parameter

Every field a configuration document may carry, with its type, its bounds and an
example. Generated from [the schema](configuration.md#editor-support), which is
generated from the Rust types that enforce the rules -- so a bound stated here is
the bound the server applies.

The dashboard links here: the (i) beside a field opens that field's section.

For how the pieces fit together, read [Configuration
reference](configuration.md); for how to use them, the guides under Usage.
"""


def fail(message: str) -> None:
    print(f"parameters-doc: {message}", file=sys.stderr)
    raise SystemExit(1)


def anchor(path: str) -> str:
    """The anchor for a parameter path.

    `proxies[].mocks[].request.url` -> `proxies-mocks-request-url`. The frontend
    builds the same string from the same path; see `frontend/src/services/docs.ts`.
    """
    return path.replace("[]", "").replace(".", "-")


class Schema:
    """The schema, with `$ref` following and `Option` unwrapping."""

    def __init__(self, document: dict[str, Any]) -> None:
        self.document = document
        self.defs: dict[str, Any] = document.get("$defs", {})

    def deref(self, node: dict[str, Any]) -> dict[str, Any]:
        ref = node.get("$ref")
        if not ref:
            return node
        return self.defs.get(ref.removeprefix("#/$defs/"), node)

    def unwrap(self, node: dict[str, Any]) -> dict[str, Any]:
        """A field's real schema: past a `$ref`, past an `Option`'s null branch.

        An `Option<T>` is emitted as `oneOf: [{type: null}, {$ref}]`, so a field's
        bounds are one level below where a reader looks for them. A union with two
        real branches -- `ByteSize` is an integer or a string -- is kept whole, with
        the description from whichever level carries one.
        """
        node = self.deref(node)
        branches = node.get("oneOf")
        if not branches:
            return node
        real = [b for b in branches if b.get("type") != "null"]
        if len(real) == 1:
            merged = dict(self.deref(real[0]))
            merged.setdefault("description", node.get("description", ""))
            return merged
        merged = dict(node)
        merged["oneOf"] = [self.deref(b) for b in real]
        return merged


def type_of(schema: Schema, node: dict[str, Any]) -> str:
    """The type, in the words a reader of YAML would use."""
    if branches := node.get("oneOf"):
        return " or ".join(type_of(schema, b) for b in branches)
    if node.get("enum"):
        return "string"
    kind = node.get("type")
    if isinstance(kind, list):
        # `Option<bool>` can arrive as `["boolean", "null"]` rather than as a
        # `oneOf`. Absent is said by the Required row, not by the type.
        named = [k for k in kind if k != "null"]
        return " or ".join(named) if named else "any"

    if kind == "array":
        item = schema.unwrap(node.get("items", {}))
        return f"list of {type_of(schema, item)}"
    if kind == "object":
        values = node.get("additionalProperties")
        if isinstance(values, dict):
            return f"map of string to {type_of(schema, schema.unwrap(values))}"
        return "object"
    return str(kind or "any")


def bounds_of(schema: Schema, node: dict[str, Any]) -> list[str]:
    """The constraints on a value, one phrase each."""
    if branches := node.get("oneOf"):
        phrases: list[str] = []
        for branch in branches:
            phrases.extend(bounds_of(schema, branch))
        return phrases

    out: list[str] = []
    if values := node.get("enum"):
        out.append("one of " + ", ".join(f"`{value}`" for value in values))
    if pattern := node.get("pattern"):
        out.append(f"matches `{pattern}`")
    low, high = node.get("minLength"), node.get("maxLength")
    if low is not None and high is not None:
        out.append(f"{low} to {high} characters")
    elif high is not None:
        out.append(f"at most {high} characters")
    elif low is not None:
        out.append(f"at least {low} characters")
    low, high = node.get("minimum"), node.get("maximum")
    if low is not None and high is not None:
        out.append(f"{fmt(low)} to {fmt(high)}")
    elif low is not None:
        out.append(f"at least {fmt(low)}")
    elif high is not None:
        out.append(f"at most {fmt(high)}")
    if node.get("additionalProperties") is False:
        out.append("no unknown keys")
    return out


def fmt(value: Any) -> str:
    """A number as YAML would write it: no trailing `.0` on a whole one."""
    if isinstance(value, float) and value.is_integer():
        return str(int(value))
    return str(value)


def example_of(schema: Schema, node: dict[str, Any]) -> Any | None:
    """An example of this value: the schema's own, or one its shape implies.

    Three shapes imply one. A boolean has two values and `true` is the interesting
    one; a map is one entry, and both halves of that entry are types with examples of
    their own; a list of scalars is one item. Anything else without an example in the
    schema gets none, because a made-up value in a reference is worse than a gap --
    it gets copied.
    """
    if examples := node.get("examples"):
        return examples[0]
    if branches := node.get("oneOf"):
        for branch in branches:
            if found := example_of(schema, branch):
                return found
    if values := node.get("enum"):
        return values[0]

    kind = node.get("type")
    if isinstance(kind, list):
        kind = next((k for k in kind if k != "null"), None)

    if kind == "boolean":
        return True
    if kind == "object":
        values_schema = node.get("additionalProperties")
        if isinstance(values_schema, dict):
            key = example_of(schema, schema.unwrap(node.get("propertyNames", {}))) or "key"
            value = example_of(schema, schema.unwrap(values_schema))
            if value is not None:
                return {str(key): value}
    if kind == "object" and node.get("properties"):
        # An object's example is the example of each field it insists on. Only the
        # required ones, so nothing here suggests a combination the server refuses --
        # `body` and `json` on a response are exclusive, and neither is required.
        built = {}
        for name in node.get("required", []):
            child = schema.unwrap(node["properties"].get(name, {}))
            found = example_of(schema, child)
            if found is None:
                return None
            built[name] = found
        return built or None
    if kind == "array":
        item = schema.unwrap(node.get("items", {}))
        found = example_of(schema, item)
        if found is not None:
            return [found]
    return None


def yaml_scalar(value: Any) -> str:
    """A scalar as YAML, quoted only where it has to be."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return fmt(value)
    if isinstance(value, list):
        return "[" + ", ".join(yaml_scalar(item) for item in value) + "]"
    text = str(value)
    needs_quotes = text == "" or text[0] in "*&!%@`>|{[#?-'\"" or ": " in text or "\\" in text
    return json.dumps(text) if needs_quotes else text


def yaml_block(value: Any, indent: int) -> list[str]:
    """A structured example as block YAML, indented to sit under its key."""
    pad = " " * indent
    if isinstance(value, dict):
        lines: list[str] = []
        for name, item in value.items():
            if isinstance(item, (dict, list)):
                lines.append(f"{pad}{name}:")
                lines += yaml_block(item, indent + 2)
            else:
                lines.append(f"{pad}{name}: {yaml_scalar(item)}")
        return lines
    if isinstance(value, list):
        lines = []
        for item in value:
            if isinstance(item, dict):
                # The dash takes two columns, so the element's keys sit two in from
                # the list itself -- and its first key shares the dash's line.
                inner = yaml_block(item, indent + 2)
                first = inner[0].lstrip()
                lines.append(f"{pad}- {first}")
                lines += inner[1:]
            else:
                lines.append(f"{pad}- {yaml_scalar(item)}")
        return lines
    return [f"{pad}{yaml_scalar(value)}"]


def example_block(path: str, value: Any) -> str:
    """The example in place, so it can be pasted into a document.

    `proxies[].mocks[].request.url` becomes the keys that reach it, with a list
    element opened by a dash wherever the path crossed a list -- and the element's
    first key on the same line as its dash, which is how a person writes YAML.
    """
    lines: list[str] = []
    indent = 0
    pending = ""
    segments = path.split(".")
    for index, segment in enumerate(segments):
        key = segment.removesuffix("[]")
        listed = segment.endswith("[]")
        head = " " * indent + pending
        if pending:
            # The dash occupies two columns; what follows it lines up after them.
            indent += 2
            pending = ""
        if index == len(segments) - 1:
            if isinstance(value, (dict, list)):
                lines.append(f"{head}{key}:")
                lines += yaml_block(value, indent + 2)
                break
            lines.append(f"{head}{key}: {yaml_scalar(value)}")
            break
        lines.append(f"{head}{key}:")
        indent += 2
        if listed:
            pending = "- "
    body = "\n".join(lines)
    return f"```yaml\n{body}\n```"


def section(
    schema: Schema, path: str, node: dict[str, Any], required: bool, level: int = 3
) -> str:
    """One parameter, as Markdown."""
    out = [f"{'#' * level} `{path}` {{ #{anchor(path)} }}", ""]
    if description := node.get("description", "").strip():
        out += [description, ""]

    rows = [("Type", type_of(schema, node)), ("Required", "yes" if required else "no")]
    if phrases := bounds_of(schema, node):
        rows.append(("Rules", "; ".join(phrases)))
    out += ["| | |", "|---|---|"]
    out += [f"| {name} | {value} |" for name, value in rows]
    out.append("")

    example = example_of(schema, node)
    if example is not None:
        out += [example_block(path, example), ""]
    return "\n".join(out)


def walk(schema: Schema, path: str, node: dict[str, Any], out: list[str]) -> None:
    """Emit a section for every parameter under `node`, depth first."""
    properties: dict[str, Any] = node.get("properties", {})
    required: list[str] = node.get("required", [])
    for name, raw in properties.items():
        child = schema.unwrap(raw)
        # The field's own description wins over the type's: it says what this field
        # is for, where the type says what the value may be.
        if raw.get("description"):
            child = {**child, "description": raw["description"]}

        child_path = f"{path}.{name}" if path else name
        out.append(section(schema, child_path, child, name in required))

        if child.get("type") == "object" and child.get("properties"):
            walk(schema, child_path, child, out)
        elif child.get("type") == "array":
            item = schema.unwrap(child.get("items", {}))
            if item.get("properties"):
                walk(schema, f"{child_path}[]", item, out)


def render(document: dict[str, Any]) -> str:
    schema = Schema(document)
    out = [HEADER]
    for name, raw in document.get("properties", {}).items():
        node = schema.unwrap(raw)
        if raw.get("description"):
            node = {**node, "description": raw["description"]}
        out.append("---\n")
        # The top-level parameter is the section: heading it twice would give the
        # page eight headings that say nothing the one below them does not.
        out.append(section(schema, name, node, name in document.get("required", []), level=2))
        if node.get("type") == "object" and node.get("properties"):
            walk(schema, name, node, out)
        elif node.get("type") == "array":
            item = schema.unwrap(node.get("items", {}))
            if item.get("properties"):
                walk(schema, f"{name}[]", item, out)
    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    if not SCHEMA.is_file():
        fail(f"{SCHEMA} is missing; run `uv run scripts/config_schema.py` first")
    document = json.loads(SCHEMA.read_text())
    generated = render(document)

    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.is_file() else ""
        if current != generated:
            fail(
                f"{OUTPUT.relative_to(ROOT)} is stale; regenerate it with "
                "`uv run scripts/parameters_doc.py`"
            )
        print(f"parameters-doc: {OUTPUT.relative_to(ROOT)} is up to date")
        return

    OUTPUT.write_text(generated)
    print(f"parameters-doc: wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
